import type { DirectusClient } from "./createDirectus";
import { createCollection, createRelation, createField } from "@directus/sdk";

export const createProduct = async (directus: DirectusClient) => {
  const product = await directus.request(
    createCollection({
      collection: "Product",
      meta: {
        collection: "Product",
        icon: null,
        note: null,
        display_template: null,
        hidden: false,
        singleton: false,
        translations: null,
        archive_field: "status",
        archive_app_filter: true,
        archive_value: "archived",
        unarchive_value: "draft",
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: "1",
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "Product",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "Product",
          field: "id",
          type: "uuid",
          schema: {
            name: "id",
            table: "Product",
            schema: "public",
            data_type: "uuid",
            is_nullable: false,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "id",
            special: ["uuid"],
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: true,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "status",
          type: "string",
          schema: {
            name: "status",
            table: "Product",
            schema: "public",
            data_type: "character varying",
            is_nullable: false,
            generation_expression: null,
            default_value: "draft",
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "status",
            special: null,
            interface: "select-dropdown",
            options: {
              choices: [
                {
                  text: "$t:published",
                  value: "published",
                },
                {
                  text: "$t:draft",
                  value: "draft",
                },
                {
                  text: "$t:archived",
                  value: "archived",
                },
                {
                  text: "$t:proposed",
                  value: "proposed",
                },
                {
                  text: "$t:rejected",
                  value: "rejected",
                },
              ],
            },
            display: "labels",
            display_options: {
              showAsDot: true,
              choices: [
                {
                  text: "$t:published",
                  value: "published",
                  foreground: "#FFFFFF",
                  background: "var(--primary)",
                },
                {
                  text: "$t:draft",
                  value: "draft",
                  foreground: "#18222F",
                  background: "#D3DAE4",
                },
                {
                  text: "$t:archived",
                  value: "archived",
                  foreground: "#FFFFFF",
                  background: "var(--warning)",
                },
              ],
            },
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "date_created",
          type: "timestamp",
          schema: {
            name: "date_created",
            table: "Product",
            schema: "public",
            data_type: "timestamp with time zone",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "date_created",
            special: ["date-created"],
            interface: "datetime",
            options: null,
            display: "datetime",
            display_options: {
              relative: true,
            },
            readonly: true,
            hidden: true,
            sort: 5,
            width: "half",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "date_updated",
          type: "timestamp",
          schema: {
            name: "date_updated",
            table: "Product",
            schema: "public",
            data_type: "timestamp with time zone",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "date_updated",
            special: ["date-updated"],
            interface: "datetime",
            options: null,
            display: "datetime",
            display_options: {
              relative: true,
            },
            readonly: true,
            hidden: true,
            sort: 6,
            width: "half",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "drupal_id",
          type: "string",
          schema: {
            name: "drupal_id",
            table: "Product",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "drupal_id",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "website",
          type: "string",
          schema: {
            name: "website",
            table: "Product",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "website",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 8,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "thumbnail",
          type: "uuid",
          schema: {
            name: "thumbnail",
            table: "Product",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "directus_files",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product",
            field: "thumbnail",
            special: ["file"],
            interface: "file-image",
            options: {
              folder: "36b0982a-ce85-4ed0-8f28-382b6651b4ca",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 9,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "medusa_id",
          type: "string",
          schema: {
            name: "medusa_id",
            table: "Product",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product",
            field: "medusa_id",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "translations",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "translations",
            special: ["translations"],
            interface: "translations",
            options: {
              languageField: "name",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 7,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "variants",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "variants",
            special: ["o2m"],
            interface: "list-o2m",
            options: {
              template: "SKU: {{sku}} {{translations}}{{translations.title}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 11,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "type",
          type: "uuid",
          schema: {
            name: "type",
            table: "Product",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductType",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product",
            field: "type",
            special: ["m2o"],
            interface: "select-dropdown-m2o",
            options: {
              template: "{{translations}}{{translations.value}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 14,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "collection",
          type: "uuid",
          schema: {
            name: "collection",
            table: "Product",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductCollection",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product",
            field: "collection",
            special: ["m2o"],
            interface: "select-dropdown-m2o",
            options: {
              template: "{{translations}}{{translations.title}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 17,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "collections",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "collections",
            special: ["m2m"],
            interface: "list-m2m",
            options: {
              template:
                "{{ProductCollection_id.translations}}{{ProductCollection_id.translations.title}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 18,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "tags",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "tags",
            special: ["m2m"],
            interface: "list-m2m",
            options: {
              template:
                "{{ProductTag_id.translations}}{{ProductTag_id.translations.value}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 15,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "options",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "options",
            special: ["o2m"],
            interface: "list-o2m",
            options: {
              template: "{{translations}}{{translations.name}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 16,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "categories",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "categories",
            special: ["m2m"],
            interface: "list-m2m",
            options: {
              template:
                "{{ProductCategory_id.translations}}{{ProductCategory_id.translations.name}}",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 19,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product",
          field: "media",
          type: "alias",
          schema: null,
          meta: {
            collection: "Product",
            field: "media",
            special: ["files"],
            interface: "files",
            options: {
              folder: "36b0982a-ce85-4ed0-8f28-382b6651b4ca",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 10,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createRelation({
      collection: "Product",
      field: "thumbnail",
      related_collection: "directus_files",
      schema: {
        constraint_name: "product_thumbnail_foreign",
        table: "Product",
        column: "thumbnail",
        foreign_key_schema: "public",
        foreign_key_table: "directus_files",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product",
        many_field: "thumbnail",
        one_collection: "directus_files",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: null,
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createCollection({
      collection: "Product_translations",
      meta: {
        collection: "Product_translations",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: "6",
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "Product_translations",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "Product_translations",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "Product_translations",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value:
              "nextval('\"Product_translations_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "Product_id",
          type: "uuid",
          schema: {
            name: "Product_id",
            table: "Product_translations",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "Product",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product_translations",
            field: "Product_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "languages_code",
          type: "string",
          schema: {
            name: "languages_code",
            table: "Product_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "languages",
            foreign_key_column: "code",
          },
          meta: {
            collection: "Product_translations",
            field: "languages_code",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "title",
          type: "string",
          schema: {
            name: "title",
            table: "Product_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "title",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "subtitle",
          type: "string",
          schema: {
            name: "subtitle",
            table: "Product_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "subtitle",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "handle",
          type: "string",
          schema: {
            name: "handle",
            table: "Product_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "handle",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "material",
          type: "string",
          schema: {
            name: "material",
            table: "Product_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "material",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_translations",
          field: "description",
          type: "text",
          schema: {
            name: "description",
            table: "Product_translations",
            schema: "public",
            data_type: "text",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_translations",
            field: "description",
            special: null,
            interface: "input-rich-text-md",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createCollection({
      collection: "Product_files",
      meta: {
        collection: "Product_files",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: "5",
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "Product_files",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "Product_files",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "Product_files",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value: "nextval('\"Product_files_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_files",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_files",
          field: "Product_id",
          type: "uuid",
          schema: {
            name: "Product_id",
            table: "Product_files",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "Product",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product_files",
            field: "Product_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_files",
          field: "directus_files_id",
          type: "uuid",
          schema: {
            name: "directus_files_id",
            table: "Product_files",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "directus_files",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product_files",
            field: "directus_files_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: null,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_files",
      field: "directus_files_id",
      related_collection: "directus_files",
      schema: {
        constraint_name: "product_files_directus_files_id_foreign",
        table: "Product_files",
        column: "directus_files_id",
        foreign_key_schema: "public",
        foreign_key_table: "directus_files",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_files",
        many_field: "directus_files_id",
        one_collection: "directus_files",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "Product_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_files",
      field: "Product_id",
      related_collection: "Product",
      schema: {
        constraint_name: "product_files_product_id_foreign",
        table: "Product_files",
        column: "Product_id",
        foreign_key_schema: "public",
        foreign_key_table: "Product",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_files",
        many_field: "Product_id",
        one_collection: "Product",
        one_field: "media",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "directus_files_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_translations",
      field: "languages_code",
      related_collection: "languages",
      schema: {
        constraint_name: "product_translations_languages_code_foreign",
        table: "Product_translations",
        column: "languages_code",
        foreign_key_schema: "public",
        foreign_key_table: "languages",
        foreign_key_column: "code",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_translations",
        many_field: "languages_code",
        one_collection: "languages",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "Product_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_translations",
      field: "Product_id",
      related_collection: "Product",
      schema: {
        constraint_name: "product_translations_product_id_foreign",
        table: "Product_translations",
        column: "Product_id",
        foreign_key_schema: "public",
        foreign_key_table: "Product",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_translations",
        many_field: "Product_id",
        one_collection: "Product",
        one_field: "translations",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "languages_code",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product",
      field: "type",
      related_collection: "ProductType",
      schema: {
        constraint_name: "product_type_foreign",
        table: "Product",
        column: "type",
        foreign_key_schema: "public",
        foreign_key_table: "ProductType",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product",
        many_field: "type",
        one_collection: "ProductType",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: null,
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product",
      field: "collection",
      related_collection: "ProductCollection",
      schema: {
        constraint_name: "product_collection_foreign",
        table: "Product",
        column: "collection",
        foreign_key_schema: "public",
        foreign_key_table: "ProductCollection",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product",
        many_field: "collection",
        one_collection: "ProductCollection",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: null,
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_ProductCollection",
      field: "Product_id",
      related_collection: "Product",
      schema: {
        constraint_name: "product_productcollection_product_id_foreign",
        table: "Product_ProductCollection",
        column: "Product_id",
        foreign_key_schema: "public",
        foreign_key_table: "Product",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_ProductCollection",
        many_field: "Product_id",
        one_collection: "Product",
        one_field: "collections",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductCollection_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_ProductCollection",
      field: "ProductCollection_id",
      related_collection: "ProductCollection",
      schema: {
        constraint_name:
          "product_productcollection_productcollection_id_foreign",
        table: "Product_ProductCollection",
        column: "ProductCollection_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductCollection",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_ProductCollection",
        many_field: "ProductCollection_id",
        one_collection: "ProductCollection",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "Product_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_ProductCategory",
      field: "Product_id",
      related_collection: "Product",
      schema: {
        constraint_name: "product_productcategory_product_id_foreign",
        table: "Product_ProductCategory",
        column: "Product_id",
        foreign_key_schema: "public",
        foreign_key_table: "Product",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_ProductCategory",
        many_field: "Product_id",
        one_collection: "Product",
        one_field: "categories",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductCategory_id",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "Product_ProductCategory",
      field: "ProductCategory_id",
      related_collection: "ProductCategory",
      schema: {
        constraint_name: "product_productcategory_productcategory_id_foreign",
        table: "Product_ProductCategory",
        column: "ProductCategory_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductCategory",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "Product_ProductCategory",
        many_field: "ProductCategory_id",
        one_collection: "ProductCategory",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "Product_id",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  return product;
};
