import type { DirectusClient } from "./createDirectus";
import { createCollection, createRelation } from "@directus/sdk";

export const createProductVariantOptions = async (directus: DirectusClient) => {
  const res = await directus.request(
    createCollection({
      collection: "ProductVariant_ProductOption",
      meta: {
        collection: "ProductVariant_ProductOption",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "ProductVariant_ProductOption",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "ProductVariant_ProductOption",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "ProductVariant_ProductOption",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value:
              "nextval('\"ProductVariant_ProductOption_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductVariant_ProductOption",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductVariant_ProductOption",
          field: "ProductVariant_id",
          type: "uuid",
          schema: {
            name: "ProductVariant_id",
            table: "ProductVariant_ProductOption",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductVariant",
            foreign_key_column: "id",
          },
          meta: {
            collection: "ProductVariant_ProductOption",
            field: "ProductVariant_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductVariant_ProductOption",
          field: "ProductOption_id",
          type: "uuid",
          schema: {
            name: "ProductOption_id",
            table: "ProductVariant_ProductOption",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductOption",
            foreign_key_column: "id",
          },
          meta: {
            collection: "ProductVariant_ProductOption",
            field: "ProductOption_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductVariant_ProductOption",
          field: "value",
          type: "string",
          schema: {
            name: "value",
            table: "ProductVariant_ProductOption",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductVariant_ProductOption",
            field: "value",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductVariant_ProductOption",
      field: "ProductOption_id",
      related_collection: "ProductOption",
      schema: {
        constraint_name:
          "productvariant_productoption_productoption_id_foreign",
        table: "ProductVariant_ProductOption",
        column: "ProductOption_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductOption",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductVariant_ProductOption",
        many_field: "ProductOption_id",
        one_collection: "ProductOption",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductVariant_id",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductVariant_ProductOption",
      field: "ProductVariant_id",
      related_collection: "ProductVariant",
      schema: {
        constraint_name:
          "productvariant_productoption_productvariant_id_foreign",
        table: "ProductVariant_ProductOption",
        column: "ProductVariant_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductVariant",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductVariant_ProductOption",
        many_field: "ProductVariant_id",
        one_collection: "ProductVariant",
        one_field: "options",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductOption_id",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  return res;
};
