import type { DirectusClient } from "./createDirectus";
import { createCollection, createRelation } from "@directus/sdk";

export const createProductOption = async (directus: DirectusClient) => {
  const res = await directus.request(
    createCollection({
      collection: "ProductOption",
      meta: {
        collection: "ProductOption",
        icon: null,
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "ProductOption",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "ProductOption",
          field: "id",
          type: "uuid",
          schema: {
            name: "id",
            table: "ProductOption",
            schema: "public",
            data_type: "uuid",
            is_nullable: false,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductOption",
            field: "id",
            special: ["uuid"],
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: true,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption",
          field: "medusa_id",
          type: "string",
          schema: {
            name: "medusa_id",
            table: "ProductOption",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductOption",
            field: "medusa_id",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption",
          field: "Product_id",
          type: "uuid",
          schema: {
            name: "Product_id",
            table: "ProductOption",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductOption",
            field: "Product_id",
            special: ["uuid"],
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: true,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption",
          field: "translations",
          type: "alias",
          schema: null,
          meta: {
            collection: "ProductOption",
            field: "translations",
            special: ["translations"],
            interface: "translations",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createCollection({
      collection: "ProductOption_translations",
      meta: {
        collection: "ProductOption_translations",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "ProductOption_translations",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "ProductOption_translations",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "ProductOption_translations",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value:
              "nextval('\"ProductOption_translations_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductOption_translations",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption_translations",
          field: "ProductOption_id",
          type: "uuid",
          schema: {
            name: "ProductOption_id",
            table: "ProductOption_translations",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductOption",
            foreign_key_column: "id",
          },
          meta: {
            collection: "ProductOption_translations",
            field: "ProductOption_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption_translations",
          field: "languages_code",
          type: "string",
          schema: {
            name: "languages_code",
            table: "ProductOption_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "languages",
            foreign_key_column: "code",
          },
          meta: {
            collection: "ProductOption_translations",
            field: "languages_code",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductOption_translations",
          field: "name",
          type: "string",
          schema: {
            name: "name",
            table: "ProductOption_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductOption_translations",
            field: "name",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: true,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductOption_translations",
      field: "languages_code",
      related_collection: "languages",
      schema: {
        constraint_name: "productoption_translations_languages_code_foreign",
        table: "ProductOption_translations",
        column: "languages_code",
        foreign_key_schema: "public",
        foreign_key_table: "languages",
        foreign_key_column: "code",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductOption_translations",
        many_field: "languages_code",
        one_collection: "languages",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductOption_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductOption_translations",
      field: "ProductOption_id",
      related_collection: "ProductOption",
      schema: {
        constraint_name: "productoption_translations_productoption_id_foreign",
        table: "ProductOption_translations",
        column: "ProductOption_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductOption",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductOption_translations",
        many_field: "ProductOption_id",
        one_collection: "ProductOption",
        one_field: "translations",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "languages_code",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductOption",
      field: "Product_id",
      related_collection: "Product",
      schema: {
        constraint_name: "productoption_product_id_foreign",
        table: "ProductOption",
        column: "Product_id",
        foreign_key_schema: "public",
        foreign_key_table: "Product",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductOption",
        many_field: "Product_id",
        one_collection: "Product",
        one_field: "options",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: null,
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  return res;
};
