import type { DirectusClient } from "./createDirectus";
import { createCollection, createRelation } from "@directus/sdk";

export const createProductCategory = async (directus: DirectusClient) => {
  const res = await directus.request(
    createCollection({
      collection: "ProductCategory",
      meta: {
        collection: "ProductCategory",
        icon: null,
        note: null,
        display_template: null,
        hidden: false,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: "2",
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "ProductCategory",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "ProductCategory",
          field: "id",
          type: "uuid",
          schema: {
            name: "id",
            table: "ProductCategory",
            schema: "public",
            data_type: "uuid",
            is_nullable: false,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory",
            field: "id",
            special: ["uuid"],
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: true,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory",
          field: "medusa_id",
          type: "string",
          schema: {
            name: "medusa_id",
            table: "ProductCategory",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory",
            field: "medusa_id",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory",
          field: "parent_category_id",
          type: "uuid",
          schema: {
            name: "parent_category_id",
            table: "ProductCategory",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductCategory",
            foreign_key_column: "id",
          },
          meta: {
            collection: "ProductCategory",
            field: "parent_category_id",
            special: null,
            interface: "select-dropdown-m2o",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory",
          field: "parent_medusa_id",
          type: "string",
          schema: {
            name: "parent_medusa_id",
            table: "ProductCategory",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory",
            field: "parent_medusa_id",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory",
          field: "translations",
          type: "alias",
          schema: null,
          meta: {
            collection: "ProductCategory",
            field: "translations",
            special: ["translations"],
            interface: "translations",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory",
          field: "category",
          type: "alias",
          schema: null,
          meta: {
            collection: "ProductCategory",
            field: "category",
            special: ["o2m"],
            interface: "list-o2m-tree-view",
            options: {
              displayTemplate: "{{translations}}{{translations.name}}",
            },
            display: "raw",
            display_options: {
              template: "{{translations}}{{translations.name}}",
            },
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createCollection({
      collection: "ProductCategory_translations",
      meta: {
        collection: "ProductCategory_translations",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "ProductCategory_translations",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "ProductCategory_translations",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value:
              "nextval('\"ProductCategory_translations_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory_translations",
          field: "ProductCategory_id",
          type: "uuid",
          schema: {
            name: "ProductCategory_id",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductCategory",
            foreign_key_column: "id",
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "ProductCategory_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory_translations",
          field: "languages_code",
          type: "string",
          schema: {
            name: "languages_code",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "languages",
            foreign_key_column: "code",
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "languages_code",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory_translations",
          field: "name",
          type: "string",
          schema: {
            name: "name",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "name",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: true,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory_translations",
          field: "handle",
          type: "string",
          schema: {
            name: "handle",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "character varying",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: 255,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "handle",
            special: null,
            interface: "input",
            options: {
              slug: true,
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: true,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "ProductCategory_translations",
          field: "description",
          type: "text",
          schema: {
            name: "description",
            table: "ProductCategory_translations",
            schema: "public",
            data_type: "text",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "ProductCategory_translations",
            field: "description",
            special: null,
            interface: "input-rich-text-md",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 6,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductCategory_translations",
      field: "languages_code",
      related_collection: "languages",
      schema: {
        constraint_name: "productcategory_translations_languages_code_foreign",
        table: "ProductCategory_translations",
        column: "languages_code",
        foreign_key_schema: "public",
        foreign_key_table: "languages",
        foreign_key_column: "code",
        on_update: "NO ACTION",
        on_delete: "SET NULL",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductCategory_translations",
        many_field: "languages_code",
        one_collection: "languages",
        one_field: null,
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "ProductCategory_id",
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductCategory_translations",
      field: "ProductCategory_id",
      related_collection: "ProductCategory",
      schema: {
        constraint_name:
          "productcategory_translations_productcategory_id_foreign",
        table: "ProductCategory_translations",
        column: "ProductCategory_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductCategory",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "CASCADE",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductCategory_translations",
        many_field: "ProductCategory_id",
        one_collection: "ProductCategory",
        one_field: "translations",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: "languages_code",
        sort_field: null,
        one_deselect_action: "delete",
      },
    })
  );

  await directus.request(
    createRelation({
      collection: "ProductCategory",
      field: "parent_category_id",
      related_collection: "ProductCategory",
      schema: {
        constraint_name: "productcategory_parent_category_id_foreign",
        table: "ProductCategory",
        column: "parent_category_id",
        foreign_key_schema: "public",
        foreign_key_table: "ProductCategory",
        foreign_key_column: "id",
        on_update: "NO ACTION",
        on_delete: "NO ACTION",
      },
      // @ts-ignore
      meta: {
        many_collection: "ProductCategory",
        many_field: "parent_category_id",
        one_collection: "ProductCategory",
        one_field: "category",
        one_collection_field: null,
        one_allowed_collections: null,
        junction_field: null,
        sort_field: null,
        one_deselect_action: "nullify",
      },
    })
  );

  await directus.request(
    createCollection({
      collection: "Product_ProductCategory",
      meta: {
        collection: "Product_ProductCategory",
        icon: "import_export",
        note: null,
        display_template: null,
        hidden: true,
        singleton: false,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: "store",
        collapse: "open",
        preview_url: null,
      },
      schema: {
        schema: "public",
        name: "Product_ProductCategory",
        comment: null,
      },
      // @ts-ignore
      fields: [
        {
          collection: "Product_ProductCategory",
          field: "id",
          type: "integer",
          schema: {
            name: "id",
            table: "Product_ProductCategory",
            schema: "public",
            data_type: "integer",
            is_nullable: false,
            generation_expression: null,
            default_value:
              "nextval('\"Product_ProductCategory_id_seq\"'::regclass)",
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: 32,
            numeric_scale: 0,
            is_unique: true,
            is_primary_key: true,
            has_auto_increment: true,
            foreign_key_schema: null,
            foreign_key_table: null,
            foreign_key_column: null,
          },
          meta: {
            collection: "Product_ProductCategory",
            field: "id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_ProductCategory",
          field: "Product_id",
          type: "uuid",
          schema: {
            name: "Product_id",
            table: "Product_ProductCategory",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "Product",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product_ProductCategory",
            field: "Product_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
        {
          collection: "Product_ProductCategory",
          field: "ProductCategory_id",
          type: "uuid",
          schema: {
            name: "ProductCategory_id",
            table: "Product_ProductCategory",
            schema: "public",
            data_type: "uuid",
            is_nullable: true,
            generation_expression: null,
            default_value: null,
            is_generated: false,
            max_length: null,
            comment: null,
            numeric_precision: null,
            numeric_scale: null,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_schema: "public",
            foreign_key_table: "ProductCategory",
            foreign_key_column: "id",
          },
          meta: {
            collection: "Product_ProductCategory",
            field: "ProductCategory_id",
            special: null,
            interface: null,
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: true,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
          },
        },
      ],
    })
  );

  return res;
};
